name: .NET CI

on:
  push:
    branches: [ main, master, develop, refactoring ]
  pull_request:
    branches: [ main, master, develop ]

concurrency:
  group: dotnet-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Restore
        run: dotnet restore Gainly_Auth.sln

      - name: Build
        run: dotnet build Gainly_Auth.sln -c Release --no-restore

      - name: Test
        run: dotnet test Gainly_Auth.sln -c Release --no-build --verbosity normal


